apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: optionix-restricted
  namespace: optionix
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "runtime/default"
    seccomp.security.alpha.kubernetes.io/defaultProfileName: "runtime/default"
    apparmor.security.beta.kubernetes.io/allowedProfileNames: "runtime/default"
    apparmor.security.beta.kubernetes.io/defaultProfileName: "runtime/default"
spec:
  # Privilege and access controls
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  allowedCapabilities: []

  # Host namespaces
  hostNetwork: false
  hostIPC: false
  hostPID: false

  # Volumes and file systems
  volumes:
    - "configMap"
    - "emptyDir"
    - "projected"
    - "secret"
    - "downwardAPI"
    - "persistentVolumeClaim"
  allowedHostPaths: []
  readOnlyRootFilesystem: true

  # Users and groups
  runAsUser:
    rule: "MustRunAsNonRoot"
  runAsGroup:
    rule: "MustRunAs"
    ranges:
      - min: 1000
        max: 65535
  supplementalGroups:
    rule: "MustRunAs"
    ranges:
      - min: 1000
        max: 65535
  fsGroup:
    rule: "MustRunAs"
    ranges:
      - min: 1000
        max: 65535

  # SELinux
  seLinux:
    rule: "RunAsAny"

  # Forbidden sysctls
  forbiddenSysctls:
    - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optionix-restricted-psp-user
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - optionix-restricted

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optionix-restricted-psp-all-serviceaccounts
roleRef:
  kind: ClusterRole
  name: optionix-restricted-psp-user
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:serviceaccounts:optionix
    apiGroup: rbac.authorization.k8s.io
